# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# For Heroku Deployment see: https://github.com/actions/heroku

name: Github | Heroku CI/CD Setup

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  test:
    name: Running Test Units
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Installing & Testing
      run: |
        npm ci
        npm run build --if-present
        npm test

  # deploy:
  #   needs: [test]
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Deploy The Sails JS App in Server via SSH
  #     uses: actions/checkout@master
  #   - name: login
  #     uses: actions/heroku@master
  #     env:
  #       HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  #     with:
  #       args: container:login
  #   - name: release
  #     uses: actions/heroku@master
  #     env:
  #       HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  #     with:
  #       args: container:release -a calm-fortress-1234 web